### ISSUE TITLE
Add the list to the awesome list

### ISSUE THREAD

**Issue by YerkoPalma** [choojs/awesome-choo#10]
Eventually, this list should be added to the [awesome list](https://github.com/sindresorhus/awesome). In that repo is recommended to add
- [x] A [badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge)
- [x] A [license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license)
- [x] And [contribution guidlines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines)

So, this issue is basically to have a reminder that those files are needed to open a PR on the awesome list repo, if we want to. Because we want to right? :smile:

**Comment by sotojuan** [comment]
I'll take care of this.

**Comment by YerkoPalma** [comment]
Ok, if you need anything just ask :)

**Comment by sotojuan** [comment]
Done!
