### ISSUE TITLE
Reorder the list

### ISSUE THREAD

**Issue by YerkoPalma** [choojs/awesome-choo#13]
The [first commit](https://github.com/YerkoPalma/awesome-choo/commit/2bebfc0fddbd08f3c056d4a182468e936730e93c) of this repo is about to be 20 days old, which means that fits the [conditions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) to be in the [awesome list of awesome lists](https://github.com/sindresorhus/awesome), but I would like to make some changes before submiting a PR.
- Reorder the sections: Right now, the table of contents has the same level of the rest of the topics, I would leave that title as an `h2` and the rest of the topics as `h3` headings.
- Reorganize some topics: Actually, the table of contents is the topic with more items than any of the others below, I think we must summarize the rest. I would merge the [Tutorials](https://github.com/YerkoPalma/awesome-choo#tutorials), [Videos](https://github.com/YerkoPalma/awesome-choo#videos) and [Articles](https://github.com/YerkoPalma/awesome-choo#articles) topics into a _Resources_ topic. We could even use some emojis to have difference between resources, like :movie_camera: for videos, :computer: for tutorials and :book: for articles.

So what do you think? any suggestions?

**Comment by yoshuawuyts** [comment]
Aye, sounds good to me!
