### ISSUE TITLE
Use `awesome-lint`

### ISSUE THREAD

**Issue by sotojuan** [choojs/awesome-choo#17]
https://github.com/sindresorhus/awesome-lint

**Comment by YerkoPalma** [comment]
Have anyone test it? I just inspected the code, and only see tests for the badge, is unfinished or I'm missing something? (Can't run it yet)

**Comment by sotojuan** [comment]
I don't know ha, just saw it and made an issue for it sorry. No rush but wanted to have it here just in case.

**Comment by YerkoPalma** [comment]
I was about to open a similar issue too haha. I think is good to have this issue open to watch that lint project. I'm also sure that the linter project is inspired in @yoshuawuyts [comment](https://github.com/sindresorhus/awesome/pull/724#issuecomment-236393086) :smile: so use the linter is obviously a MUST for this repo

**Comment by sindresorhus** [comment]
I've been [planning](https://github.com/sindresorhus/awesome/issues/569) to make it for a while, but @yoshuawuyts' comment did indeed trigger me to finally build it :)

Could use some feedback on it over at: https://github.com/sindresorhus/awesome-lint/issues/3

There's currently only one Awesome specific rule, but I've [enabled many built-in `remark-lint` rules](https://github.com/sindresorhus/awesome-lint/blob/master/config.js).

**Comment by YerkoPalma** [comment]
The `awesome-lint`er rules were applied [here](https://github.com/YerkoPalma/awesome-choo/commit/78c486c00395f0f1001404ebf557a27090e3aea8), so I'm closing this issue for now.
