### ISSUE TITLE
Curation and style

### ISSUE THREAD

**Issue by sotojuan** [choojs/awesome-choo#2]
First of all I hope this doesn't come off as rude—I'm sure you have the best intentions for this repo. That said, a common problem with awesome lists is that they lack curation (meaning anything gets added and broken/old stuff doesn't get removed) and the style isn't consistent and neat.

choo is young and we have the chance of making this awesome list clean and always up to date. I'm offering my time to curate and edit as needed if you give me commit access.

For linting, we can use [these rules](https://github.com/avajs/awesome-ava/blob/master/contributing.md) and the stuff in [this issue](https://github.com/sindresorhus/awesome/issues/569).

Thanks!

**Comment by YerkoPalma** [comment]
> First of all I hope this doesn't come off as rude

Not at all :)

> meaning anything gets added and broken/old stuff doesn't get removed

For some context, this repo was born from [this issue](https://github.com/yoshuawuyts/choo/issues/132), as you can see in that thread, I blindly added some choo links, so they obviously need to be reviewed.

> For linting, we can use these rules and the stuff in this issue.

Also on that thread I proposed to use some dedicated contributing guide, the github issues and PR templates seems to be a good option.

> I'm offering my time to curate and edit as needed if you give me commit access.

Sounds good to me, I will also give commits rights to @yoshuawuyts

**Comment by YerkoPalma** [comment]
@yoshuawuyts and @sotojuan both added as collaborators :tada:

**Comment by sotojuan** [comment]
Thanks! I don't think we need to remove anything because choo is so new—I just meant in the future as it hopefully gets bigger.

**Comment by yoshuawuyts** [comment]
@YerkoPalma wooh, thanks! :grin:
